# Build stage
FROM alpine
WORKDIR /app
RUN apk add curl
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
COPY . .
CMD [ "/app/migrate.sh" ]


