// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: general.sql

package db

import (
	"context"
)

const validateDB = `-- name: ValidateDB :one
SELECT 1+1
`

func (q *Queries) ValidateDB(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, validateDB)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
