// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BlockSession(ctx context.Context, id uuid.UUID) (Session, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteVideo(ctx context.Context, videoIdentifier string) (Video, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUsersVideosCount(ctx context.Context, owner string) (int64, error)
	GetVideo(ctx context.Context, arg GetVideoParams) (Video, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error)
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) (User, error)
	ValidateDB(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
